version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: mapminder_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mapminderpass123
      MYSQL_DATABASE: mapminder
      MYSQL_USER: mapminder
      MYSQL_PASSWORD: mapminderpass123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
